#!/bin/bash


# link to oxford word list
ox_lst="$HOME/.config/oxford_3000_5000.list"
# YOUR language
lang_my='ru'
# FOREIGN language (lang of words in dictionary)
lang_foreign='en'


# check if list of words exists
if [ ! -f "$ox_lst" ]; then
  echo "Oxford word list path \"$ox_lst\" is not correct. Change path in this script or create word list by this path."
  exit 1
fi  

# help stuff
if [[ "$1" == '--help' ]]; then
  echo 'USAGE:'
  echo '  nw [OPTIONS]'
  echo ''
  echo 'DESCRIPTION:'
  echo '  New random word from a list of words. Might be helpful for learning foreign language. Remove a word from the list when you sure you know it'
  echo ''
  echo 'OPTIONS:'
  echo -e "  -d      enable dictionary mode for translate-shell" 
  echo -e "  -p      disable bat's paging"
  echo -e "  -P      always bat's paging"
  echo -e "  -e      edit dictionary"
  echo -e "  -b      edit this bash script"
  echo -e "  --help  display this help and exit"
  echo ''
  echo 'EXAMPLES:'
  echo -e '  nw      Basically show new word'
  echo -e '  nw -d   Show new word in dictionary mode'
  echo -e '  nw -e   Edit your list of words'
  echo -e '  nw -b   Edit this bash script'
  echo -e '  while true; do nw -P; done   Infinite repeat of new words with paging'

  exit 0
fi


# options handling
while getopts :dpPeb arg; do
  case "${arg}" in
    d)transarg='-d';;
    p)batarg='--paging=never';;
    P)batarg='--paging=always';;
    e)vi $ox_lst; exit 0;;
    b)vi $0; exit 0;;
  esac
done

# get line by its number
get_n_line() {
  sed -n "$1p" "$ox_lst"
}
# get random number
get_rand() {
  shuf -i $1-$2 -n 1
}

# count of lines in list of words
count_of_lines="$(cat "$ox_lst" | wc -l)"
# selected random word
rand_word="$(get_n_line $(get_rand 1 $count_of_lines))"

# finally show tranlation
trans -e google $transarg $lang_foreign:$lang_my $rand_word | batcat $batarg

